### ISSUE TITLE
Improve usage guide

### ISSUE THREAD

**Issue by rluvaton** [rluvaton/bulk-npm-publish#32]
Improve in the README the usage guide

**Comment by rluvaton** [comment]
https://github.com/verdaccio/verdaccio/issues/1740#issuecomment-596731318

**Comment by rluvaton** [comment]
Maybe add animation of the usage

**Comment by juanpicado** [comment]
I'd add an answer here https://stackoverflow.com/questions/55258268/how-to-migrate-private-verdaccio-npm-registry-to-another-server/

**Comment by rluvaton** [comment]
@juanpicado what do you think about the new animation, is it helpful?

**Comment by juanpicado** [comment]
Thanks @rluvaton sorry I did not see your previous notification.
