### ISSUE TITLE
The library crash on start

### ISSUE THREAD

**Issue by juanpicado** [rluvaton/bulk-npm-publish#33]
After install and just run `bulk-npm-publish` the library crash. To me seems a TS transpiler issue.

Environment:

* nvm: v13.1.0/v12/v10
* MacOS 

```
➜ bulk-npm-publish
 line 1: use strict: command not found
 line 2: syntax error near unexpected token `('
 line 2: `var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {'
```

**Comment by juanpicado** [comment]
I think you need to add the right header for the distributable, for instance, a file named `bulk-npm-publish` in the `bin` folder usually is the way
```
#!/usr/bin/env node

require('../dist/index.js');
```
and then

```
  "bin": {
    "bulk-npm-publish": "./bin/bulk-npm-publish"
  },
```
I haven't try, but seems node.js does not understand the content of the index.js

**Comment by juanpicado** [comment]
If I build and run your library with `node`, then seems works fine.

```
bulk-npm-publish on  master [?] is 📦 v1.1.0 via ⬢ v13.1.0 at ☸️  docker-desktop took 6s 
➜ node dist/index.js
info: ⏳ Starting... ⏳
info: 🔧 User configuration
info: Getting user input by the console
? What's the storage path to publish? › 
```

**Comment by rluvaton** [comment]
I tested it on my Windows & Linux machine
@juanpicado Can you please check if the problem solved for you 🤔

**Comment by juanpicado** [comment]
@rluvaton cool ! now it works fine
